import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Seed a super admin user for local development only
  // Password hash below is bcrypt of 'NowRift_Admin_Dev!'
  // NEVER use this in production
  await prisma.user.upsert({
    where: { email: 'admin@nowrift.dev' },
    update: {},
    create: {
      email: 'admin@nowrift.dev',
      password_hash: '$2b$12$bmmqlJmw7my47weuH/2VP.SvrXupTAJzgW37GDMCMYRSdI8Jn5IAq',
      display_name: 'NowRift Admin',
      status: 'active',
    },
  });
  console.log('Super admin seeded');

  // Channels are already seeded by migration 003
  // Verify they exist or seed them if missing
  const channelCount = await prisma.channel.count();
  console.log(`Channels in DB: ${channelCount} (should be 7)`);

  // If channels are empty, let's seed them to guarantee they exist
  if (channelCount === 0) {
    const channelsToSeed = [
      { name: 'AI Models', slug: 'ai-models', description: 'Large language models, releases, benchmarks, and AI product launches', color_hex: '#FF3D3D', icon_name: 'ti-brain', sort_order: 1 },
      { name: 'Developers', slug: 'developers', description: 'APIs, frameworks, tooling, and developer ecosystem news', color_hex: '#4FA3F5', icon_name: 'ti-code', sort_order: 2 },
      { name: 'Cybersecurity', slug: 'cybersecurity', description: 'Threat reports, zero-days, enterprise security, and encryption', color_hex: '#EF9F27', icon_name: 'ti-shield-lock', sort_order: 3 },
      { name: 'Hardware', slug: 'hardware', description: 'Chips, custom silicon, quantum computing, and server tech', color_hex: '#8B8BA0', icon_name: 'ti-cpu', sort_order: 4 },
      { name: 'Founders', slug: 'founders', description: 'Venture funding, pitch decks, enterprise SaaS, and startup strategy', color_hex: '#B47FDD', icon_name: 'ti-rocket', sort_order: 5 },
      { name: 'Creators', slug: 'creators', description: 'Generative design, video, code assistants, and productivity tools', color_hex: '#5DCAA5', icon_name: 'ti-brush', sort_order: 6 },
      { name: 'Data Science', slug: 'data-science', description: 'Data pipelines, analytics platforms, pandas, and SQL tools', color_hex: '#F09595', icon_name: 'ti-database', sort_order: 7 }
    ];

    for (const chan of channelsToSeed) {
      await prisma.channel.create({ data: chan });
    }
    console.log('Seeded 7 core channels');
  }

  // Seed 5 sample articles for UI development
  const aiChannel = await prisma.channel.findFirst({
    where: { slug: 'ai-models' },
  });

  if (aiChannel) {
    for (let i = 1; i <= 5; i++) {
      const art = await prisma.article.upsert({
        where: { slug: `sample-article-${i}` },
        update: {},
        create: {
          slug: `sample-article-${i}`,
          headline: `Sample Article ${i} — AI and Technology Development Update`,
          deck: `This is a sample article for development testing. It covers important developments in AI and technology that affect developers, security professionals, and founders.`,
          body_html: `<p>Full article body content goes here. This is placeholder text for development testing of the NowRift article layout and typography.</p><p>The actual content will be generated by the AI synthesis agent pipeline.</p>`,
          so_what_dev: `Developer impact: This development directly affects how you build AI-powered applications. Consider reviewing your current implementation approach.`,
          so_what_security: `Security risk: Review your threat models in light of this development. Update your security posture accordingly.`,
          so_what_founders: `Founder opportunity: This creates a new market opportunity for startups focused on this space.`,
          status: 'published',
          is_breaking: i === 1,
          relevance_score: 0.85 + i * 0.02,
          channel_id: aiChannel.id,
          meta_title: `Sample Article ${i} | NowRift`,
          meta_description: `Development test article ${i} for NowRift platform testing.`,
          view_count: i * 340,
          published_at: new Date(Date.now() - i * 3600000),
        },
      });

      // Seed an audit record for each article to satisfy AigenAuditPill requirements
      await prisma.aigenAuditRecord.upsert({
        where: { article_id: art.id },
        update: {},
        create: {
          article_id: art.id,
          model_used: 'Claude 3.5 Sonnet',
          source_count: i + 1,
          source_urls: ['https://example.com/source-1', 'https://example.com/source-2'],
          max_similarity_score: 0.12,
          copyright_passed: true,
        }
      });
    }
    console.log('Seeded 5 sample articles with audits');
  }

  // Seed 3 sample grants for grants hub development
  await prisma.grant.upsert({
    where: { slug: 'sample-innovate-uk-ai-2026' },
    update: {},
    create: {
      slug: 'sample-innovate-uk-ai-2026',
      title: 'Innovate UK — AI Innovation for Future Economy',
      funder_name: 'Innovate UK',
      funder_url: 'https://www.ukri.org/councils/innovate-uk/',
      status: 'open',
      funding_min: 200000,
      funding_max: 1500000,
      currency: 'GBP',
      geo_scope: ['uk'],
      sectors: ['ai', 'edtech', 'healthtech'],
      eligibility_tags: ['startup', 'sme'],
      summary: 'Funding for UK businesses developing AI solutions that demonstrably improve economic productivity.',
      deadline: new Date('2026-08-30'),
      apply_url: 'https://www.ukri.org/',
      is_featured: true,
      published_at: new Date(),
    },
  });

  await prisma.grant.upsert({
    where: { slug: 'sample-tef-2026' },
    update: {},
    create: {
      slug: 'sample-tef-2026',
      title: 'Tony Elumelu Foundation Entrepreneurship Programme 2026',
      funder_name: 'Tony Elumelu Foundation',
      funder_url: 'https://www.tonyelumelufoundation.org/',
      status: 'open',
      funding_min: 5000,
      funding_max: 5000,
      currency: 'USD',
      geo_scope: ['nigeria', 'africa'],
      sectors: ['ai', 'agritech', 'fintech', 'healthtech'],
      eligibility_tags: ['startup'],
      summary: '$5,000 non-refundable seed capital plus 12 weeks of mentorship for African entrepreneurs.',
      deadline: new Date('2026-07-31'),
      apply_url: 'https://www.tonyelumelufoundation.org/',
      published_at: new Date(),
    },
  });

  await prisma.grant.upsert({
    where: { slug: 'sample-sovereign-ai-fund-2026' },
    update: {},
    create: {
      slug: 'sample-sovereign-ai-fund-2026',
      title: 'UK Sovereign AI Fund — First Cohort Applications',
      funder_name: 'DSIT · UK Government',
      funder_url: 'https://www.gov.uk/',
      status: 'closing_soon',
      funding_min: 100000,
      funding_max: 500000,
      currency: 'GBP',
      geo_scope: ['uk'],
      sectors: ['ai', 'edtech', 'healthtech', 'fintech'],
      eligibility_tags: ['startup', 'sme'],
      summary: 'First cohort of the Sovereign AI Fund supporting UK-based AI companies building in priority sectors.',
      deadline: new Date('2026-06-30'),
      apply_url: 'https://www.gov.uk/',
      is_featured: true,
      published_at: new Date(),
    },
  });

  console.log('Seeded 3 sample grants');
  console.log('Seed complete. Run npm run dev to start development.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
