import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Seed a super admin user for local development only
  // Password hash below is bcrypt of 'NowRift_Admin_Dev!'
  // NEVER use this in production
  await prisma.user.upsert({
    where: { email: 'admin@nowrift.dev' },
    update: {},
    create: {
      email: 'admin@nowrift.dev',
      password_hash: '$2b$12$bmmqlJmw7my47weuH/2VP.SvrXupTAJzgW37GDMCMYRSdI8Jn5IAq',
      display_name: 'NowRift Admin',
      status: 'active',
    },
  });
  console.log('Super admin seeded');

  // Channels are already seeded by migration 003
  // Verify they exist or seed them if missing
  const channelCount = await prisma.channel.count();
  console.log(`Channels in DB: ${channelCount} (should be 7)`);

  // If channels are empty, let's seed them to guarantee they exist
  if (channelCount === 0) {
    const channelsToSeed = [
      { name: 'AI Models', slug: 'ai-models', description: 'Large language models, releases, benchmarks, and AI product launches', color_hex: '#FF3D3D', icon_name: 'ti-brain', sort_order: 1 },
      { name: 'Developers', slug: 'developers', description: 'APIs, frameworks, tooling, and developer ecosystem news', color_hex: '#4FA3F5', icon_name: 'ti-code', sort_order: 2 },
      { name: 'Cybersecurity', slug: 'cybersecurity', description: 'Threat reports, zero-days, enterprise security, and encryption', color_hex: '#EF9F27', icon_name: 'ti-shield-lock', sort_order: 3 },
      { name: 'Hardware', slug: 'hardware', description: 'Chips, custom silicon, quantum computing, and server tech', color_hex: '#8B8BA0', icon_name: 'ti-cpu', sort_order: 4 },
      { name: 'Founders', slug: 'founders', description: 'Venture funding, pitch decks, enterprise SaaS, and startup strategy', color_hex: '#B47FDD', icon_name: 'ti-rocket', sort_order: 5 },
      { name: 'Creators', slug: 'creators', description: 'Generative design, video, code assistants, and productivity tools', color_hex: '#5DCAA5', icon_name: 'ti-brush', sort_order: 6 },
      { name: 'Data Science', slug: 'data-science', description: 'Data pipelines, analytics platforms, pandas, and SQL tools', color_hex: '#F09595', icon_name: 'ti-database', sort_order: 7 }
    ];

    for (const chan of channelsToSeed) {
      await prisma.channel.create({ data: chan });
    }
    console.log('Seeded 7 core channels');
  }

  // Seed 5 sample articles for UI development
  const aiChannel = await prisma.channel.findFirst({
    where: { slug: 'ai-models' },
  });

  if (aiChannel) {
    for (let i = 1; i <= 5; i++) {
      const art = await prisma.article.upsert({
        where: { slug: `sample-article-${i}` },
        update: {},
        create: {
          slug: `sample-article-${i}`,
          headline: `Sample Article ${i} — AI and Technology Development Update`,
          deck: `This is a sample article for development testing. It covers important developments in AI and technology that affect developers, security professionals, and founders.`,
          body_html: `<p>Full article body content goes here. This is placeholder text for development testing of the NowRift article layout and typography.</p><p>The actual content will be generated by the AI synthesis agent pipeline.</p>`,
          so_what_dev: `Developer impact: This development directly affects how you build AI-powered applications. Consider reviewing your current implementation approach.`,
          so_what_security: `Security risk: Review your threat models in light of this development. Update your security posture accordingly.`,
          so_what_founders: `Founder opportunity: This creates a new market opportunity for startups focused on this space.`,
          status: 'published',
          is_breaking: i === 1,
          relevance_score: 0.85 + i * 0.02,
          channel_id: aiChannel.id,
          meta_title: `Sample Article ${i} | NowRift`,
          meta_description: `Development test article ${i} for NowRift platform testing.`,
          view_count: i * 340,
          published_at: new Date(Date.now() - i * 3600000),
        },
      });

      // Seed an audit record for each article to satisfy AigenAuditPill requirements
      await prisma.aigenAuditRecord.upsert({
        where: { article_id: art.id },
        update: {},
        create: {
          article_id: art.id,
          model_used: 'Claude 3.5 Sonnet',
          source_count: i + 1,
          source_urls: ['https://example.com/source-1', 'https://example.com/source-2'],
          max_similarity_score: 0.12,
          copyright_passed: true,
        }
      });
    }
    console.log('Seeded 5 sample articles with audits');
  }

  // Seed 3 sample grants for grants hub development
  await prisma.grant.upsert({
    where: { slug: 'sample-innovate-uk-ai-2026' },
    update: {},
    create: {
      slug: 'sample-innovate-uk-ai-2026',
      title: 'Innovate UK — AI Innovation for Future Economy',
      funder_name: 'Innovate UK',
      funder_url: 'https://www.ukri.org/councils/innovate-uk/',
      status: 'open',
      funding_min: 200000,
      funding_max: 1500000,
      currency: 'GBP',
      geo_scope: ['uk'],
      sectors: ['ai', 'edtech', 'healthtech'],
      eligibility_tags: ['startup', 'sme'],
      summary: 'Funding for UK businesses developing AI solutions that demonstrably improve economic productivity.',
      deadline: new Date('2026-08-30'),
      apply_url: 'https://www.ukri.org/',
      is_featured: true,
      published_at: new Date(),
    },
  });

  await prisma.grant.upsert({
    where: { slug: 'sample-tef-2026' },
    update: {},
    create: {
      slug: 'sample-tef-2026',
      title: 'Tony Elumelu Foundation Entrepreneurship Programme 2026',
      funder_name: 'Tony Elumelu Foundation',
      funder_url: 'https://www.tonyelumelufoundation.org/',
      status: 'open',
      funding_min: 5000,
      funding_max: 5000,
      currency: 'USD',
      geo_scope: ['nigeria', 'africa'],
      sectors: ['ai', 'agritech', 'fintech', 'healthtech'],
      eligibility_tags: ['startup'],
      summary: '$5,000 non-refundable seed capital plus 12 weeks of mentorship for African entrepreneurs.',
      deadline: new Date('2026-07-31'),
      apply_url: 'https://www.tonyelumelufoundation.org/',
      published_at: new Date(),
    },
  });

  await prisma.grant.upsert({
    where: { slug: 'sample-sovereign-ai-fund-2026' },
    update: {},
    create: {
      slug: 'sample-sovereign-ai-fund-2026',
      title: 'UK Sovereign AI Fund — First Cohort Applications',
      funder_name: 'DSIT · UK Government',
      funder_url: 'https://www.gov.uk/',
      status: 'closing_soon',
      funding_min: 100000,
      funding_max: 500000,
      currency: 'GBP',
      geo_scope: ['uk'],
      sectors: ['ai', 'edtech', 'healthtech', 'fintech'],
      eligibility_tags: ['startup', 'sme'],
      summary: 'First cohort of the Sovereign AI Fund supporting UK-based AI companies building in priority sectors.',
      deadline: new Date('2026-06-30'),
      apply_url: 'https://www.gov.uk/',
      is_featured: true,
      published_at: new Date(),
    },
  });

  console.log('Seeded 3 sample grants');

  // Seed dynamic tools
  const toolsToSeed = [
    {
      slug: 'deepseek-r1',
      name: 'DeepSeek-R1',
      description: 'Open-source frontier reasoning model that achieves performance parity with OpenAI\'s o1 in math, code, and reasoning tasks.',
      category: 'AI Models',
      url: 'https://deepseek.com',
      icon: 'IconBrain',
      color: '#FF3D3D',
      released_at: new Date('2025-01-20'),
    },
    {
      slug: 'claude-3-7-sonnet',
      name: 'Claude 3.7 Sonnet',
      description: 'Anthropic\'s hybrid reasoning frontier model that natively balances instantaneous responses with deep, extended-compute logical thinking.',
      category: 'AI Models',
      url: 'https://anthropic.com',
      icon: 'IconBrain',
      color: '#FF3D3D',
      released_at: new Date('2025-02-24'),
    },
    {
      slug: 'openai-o3-mini',
      name: 'OpenAI o3-mini',
      description: 'Speed-oriented reasoning model designed for high-performance coding, complex math, and low-latency API integration.',
      category: 'AI Models',
      url: 'https://openai.com',
      icon: 'IconBrain',
      color: '#FF3D3D',
      released_at: new Date('2025-02-10'),
    },
    {
      slug: 'gemini-2-5-flash',
      name: 'Gemini 2.5 Flash',
      description: 'Google\'s ultra-fast, high-context multimodal model designed for real-time agentic actions and audio-video processing.',
      category: 'AI Models',
      url: 'https://deepmind.google',
      icon: 'IconBrain',
      color: '#FF3D3D',
      released_at: new Date('2025-02-05'),
    },
    {
      slug: 'grok-3',
      name: 'Grok 3',
      description: 'xAI\'s massive-scale frontier model, featuring real-time access to global data streams and deep scientific reasoning capabilities.',
      category: 'AI Models',
      url: 'https://x.ai',
      icon: 'IconBrain',
      color: '#FF3D3D',
      released_at: new Date('2025-02-18'),
    },
    {
      slug: 'devin',
      name: 'Devin',
      description: 'The world\'s first autonomous AI software engineer, capable of building, testing, and deploying complex software systems independently.',
      category: 'AI Agents',
      url: 'https://cognition.ai',
      icon: 'IconTerminal2',
      color: '#4FA3F5',
      released_at: new Date('2024-03-12'),
    },
    {
      slug: 'cursor',
      name: 'Cursor',
      description: 'The AI-first code editor built around VS Code. Fast, secure, and supports advanced agentic integrations.',
      category: 'AI Coding',
      url: 'https://cursor.sh',
      icon: 'IconCode',
      color: '#4FA3F5',
      released_at: new Date('2023-03-01'),
    },
    {
      slug: 'v0-by-vercel',
      name: 'v0 by Vercel',
      description: 'Generative UI system by Vercel. Generates production-ready React code with Tailwind CSS from prompts.',
      category: 'AI Coding',
      url: 'https://v0.dev',
      icon: 'IconCpu',
      color: '#4FA3F5',
      released_at: new Date('2023-09-01'),
    },
    {
      slug: 'bolt-new',
      name: 'Bolt.new',
      description: 'Full-stack web development in the browser. Run, debug, and deploy full applications using LLM assistance.',
      category: 'AI Coding',
      url: 'https://bolt.new',
      icon: 'IconTerminal2',
      color: '#4FA3F5',
      released_at: new Date('2024-10-01'),
    },
    {
      slug: 'shodan',
      name: 'Shodan',
      description: 'The search engine for internet-connected devices. Critical for network mapping and vulnerability assessment.',
      category: 'Cybersecurity',
      url: 'https://shodan.io',
      icon: 'IconSearch',
      color: '#EF9F27',
      released_at: new Date('2009-11-01'),
    },
    {
      slug: 'burp-suite',
      name: 'Burp Suite',
      description: 'Industry-standard web vulnerability scanner and penetration testing tool. Indispensable for security audits.',
      category: 'Cybersecurity',
      url: 'https://portswigger.net',
      icon: 'IconShieldLock',
      color: '#EF9F27',
      released_at: new Date('2003-01-01'),
    },
    {
      slug: 'linear',
      name: 'Linear',
      description: 'The issue tracker that teams actually love using. Fast, keyboard-shortcuts driven, and extremely polished.',
      category: 'Startup Stack',
      url: 'https://linear.app',
      icon: 'IconListCheck',
      color: '#B47FDD',
      released_at: new Date('2019-06-01'),
    },
    {
      slug: 'stripe',
      name: 'Stripe',
      description: 'Payment infrastructure for the internet. Startups use it to accept payments, manage subscriptions, and scale.',
      category: 'Startup Stack',
      url: 'https://stripe.com',
      icon: 'IconCreditCard',
      color: '#B47FDD',
      released_at: new Date('2011-09-01'),
    },
    {
      slug: 'midjourney',
      name: 'Midjourney',
      description: 'Frontier text-to-image generative model. Excellent for drafting media assets, mockups, and visual inspirations.',
      category: 'Creative AI',
      url: 'https://midjourney.com',
      icon: 'IconPalette',
      color: '#5DCAA5',
      released_at: new Date('2022-07-12'),
    },
    {
      slug: 'elevenlabs',
      name: 'ElevenLabs',
      description: 'State-of-the-art voice generation and text-to-speech platform. Curated for developers building voice agents.',
      category: 'Creative AI',
      url: 'https://elevenlabs.io',
      icon: 'IconVolume',
      color: '#5DCAA5',
      released_at: new Date('2023-01-01'),
    },
    {
      slug: 'jsonplaceholder',
      name: 'JSONPlaceholder',
      description: 'Free, fake, and reliable online REST API for testing and prototyping with zero configuration.',
      category: 'Free APIs',
      url: 'https://jsonplaceholder.typicode.com',
      icon: 'IconSourceCode',
      color: '#00E5FF',
      released_at: new Date('2013-01-01'),
    },
    {
      slug: 'openweathermap-api',
      name: 'OpenWeatherMap API',
      description: 'Free, simple weather data API providing current, forecast, and historical weather data for any location.',
      category: 'Free APIs',
      url: 'https://openweathermap.org/api',
      icon: 'IconCpu',
      color: '#00E5FF',
      released_at: new Date('2012-01-01'),
    },
    {
      slug: 'coingecko-api',
      name: 'CoinGecko API',
      description: 'Free, robust cryptocurrency data API tracking prices, volume, market cap, and developer stats.',
      category: 'Free APIs',
      url: 'https://www.coingecko.com/en/api',
      icon: 'IconCreditCard',
      color: '#00E5FF',
      released_at: new Date('2018-01-01'),
    },
    {
      slug: 'github-api',
      name: 'GitHub REST API',
      description: 'Free developer API to programmatically interact with repositories, user profiles, issues, and gists.',
      category: 'Free APIs',
      url: 'https://docs.github.com/en/rest',
      icon: 'IconCode',
      color: '#00E5FF',
      released_at: new Date('2011-01-01'),
    },
    {
      slug: 'rest-countries',
      name: 'REST Countries API',
      description: 'Free, public API providing comprehensive information about countries, regions, population, and currencies.',
      category: 'Free APIs',
      url: 'https://restcountries.com',
      icon: 'IconSearch',
      color: '#00E5FF',
      released_at: new Date('2013-01-01'),
    },
    {
      slug: 'httpbin',
      name: 'HTTPBin',
      description: 'A simple, free HTTP Request & Response Service, perfect for testing various HTTP methods, headers, and status codes.',
      category: 'Free APIs',
      url: 'https://httpbin.org',
      icon: 'IconTerminal2',
      color: '#00E5FF',
      released_at: new Date('2011-01-01'),
    },
    {
      slug: 'public-apis',
      name: 'Public APIs Directory',
      description: 'A collective index of thousands of free, public APIs for developers across tech, finance, weather, and science.',
      category: 'Free APIs',
      url: 'https://github.com/public-apis/public-apis',
      icon: 'IconListCheck',
      color: '#00E5FF',
      released_at: new Date('2016-01-01'),
    }
  ];

  for (const tool of toolsToSeed) {
    await prisma.tool.upsert({
      where: { slug: tool.slug },
      update: tool,
      create: tool,
    });
  }
  console.log('Seeded 22 developer and AI tools');
  console.log('Seed complete. Run npm run dev to start development.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
